name: build-libantimoyjs-github-actions
run-name: ${{ github.actor }} is building libantimonyjs
on: [push]
jobs:
  build-new-version-antimonyjs:
    runs-on: ubuntu-latest
    env:
       EMSDK: emsdk
       EMSDK_NODE: emsdk/node/16.20.0_64bit/bin/node
       LIBANTIMONYJS_DIR: libantimonyjs
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - name: get emscripten
        run: git clone https://github.com/emscripten-core/emsdk.git 
      - name: list files
        run: ls
        working-directory: emsdk
      - name: change emsdk script permissions
        run: chmod +x emsdk
        working-directory: emsdk
      - name: install emscripten sdk
        run: ./emsdk install 3.1.20
        working-directory: emsdk
      - name: activate emscripten
        run: ./emsdk activate 3.1.20
        working-directory: emsdk
      - run: pwd
      - run: echo "$GITHUB_WORKSPACE/emsdk/upstream/emscripten" >> $GITHUB_PATH
      - run: echo "$GITHUB_WORKSPACE/emsdk" >> $GITHUB_PATH
      - name: set permissions for emsdk_env.sh, not necessary??
        run: chmod +x emsdk/emsdk_env.sh
      - name: Set up emscripten environment, does not work, remove.
        run: ./emsdk_env.sh
        working-directory: emsdk
      - run: echo $GITHUB_PATH
      - name: confirm emscripten works
        run: emcc -v
      - run: echo $PATH
      - run: echo $EMSDK
      - run: echo $EMSDK_NODE
      - run: echo $LIBANTIMONY_JS
      - run: mkdir install
      - run: wget https://github.com/libexpat/libexpat/releases/download/R_2_2_10/expat-2.2.10.tar.bz2
      - run: tar -xf expat-2.2.10.tar.bz2
      - run: mv expat-2.2.10 expat
      - name: make expat build dir
        run: mkdir build
        working-directory: expat
      - name: build expat lib
        run: emcmake cmake .. -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install/expat
        working-directory: expat/build
      - name: make expat lib
        run: emmake make
        working-directory: expat/build  
      - name: install expat lib
        run: emmake make install
        working-directory: expat/build
        
      
        
        