name: build-libantimoyjs-github-actions
run-name: ${{ github.actor }} is building libantimonyjs
on: [push]
jobs:
  build-new-version-antimonyjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: get emscripten
        run: git clone https://github.com/emscripten-core/emsdk.git 
      - name: list files
        run: ls
        working-directory: emsdk
      - name: change emsdk script permissions
        run: chmod +x emsdk
        working-directory: emsdk
      - name: install emscripten sdk
        run: ./emsdk install 3.1.20
        working-directory: emsdk
      - run: pwd
      - name: Show files changed
        run: cat $HOME/
        