name: build-libantimoyjs-github-actions
run-name: ${{ github.actor }} is building libantimonyjs
on: [push]
jobs:
  build-new-version-antimonyjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: get emscripten
        run: git clone https://github.com/emscripten-core/emsdk.git 
      - name: list files
        run: ls
        working-directory: emsdk
      - name: change emsdk script permissions
        run: chmod +x emsdk
        working-directory: emsdk
      - name: install emscripten sdk
        run: ./emsdk install 3.1.20
        working-directory: emsdk
      - name: activate emscripten
        run: ./emsdk activate 3.1.20
        working-directory: emsdk
      - run: pwd
      - run: echo $HOME
      - name: set permissions for emsdk_env.sh
        run: chmod +x emsdk/emsdk_env.sh
      - name: Set up emscripten environment
        run: ./emsdk_env.sh
        working-directory: emsdk
      - name: confirm emscripten works
        run: ./emcc -v
        working-directory: emsdk/upstream/emscripten
      - run: echo $PATH
        
        