name: build-test-release-directory
run-name: ${{ github.actor }} is testing release-directory
on: [push]
jobs:
  build-test-release-directory:
    runs-on: ubuntu-latest
    env:
       EMSDK: emsdk
       EMSDK_NODE: emsdk/node/16.20.0_64bit/bin/node
       SBML_VERS: "5.20.0"
       ANT_VERS: "2.13.3"
    steps:
      - uses: actions/checkout@v4
      - name: Commit new libantimony files
        run: mkdir v$ANT_VERS
        working-directory: release
      - name: new libantimony files
        run: ls
        working-directory: release 
      - name: new libantimony files
        run: ls > list.txt
        working-directory: release        
      - name: Copy list.txt to release dir
        run: cp list.txt $GITHUB_WORKSPACE/release/v$ANT_VERS
        working-directory: release
      - name: check file copy
        run: ls
        working-directory: release/v$ANT_VERS
      
        
        
      
        
        